formatting

diff --git a/bin/gcloud-switch b/bin/gcloud-switch
--- a/bin/gcloud-switch
+++ b/bin/gcloud-switch
@@ -12,17 +12,18 @@
 # just run it and see..
 
 declare -a deps=(
-  awk
-  cut
-  fzf
-  gcloud
+	awk
+	cut
+	fzf
+	gcloud
 )
 
 for dep in "${deps[@]}"; do
-  hash ${dep} 2>/dev/null
-  if [ $? -gt 0 ]; then
-    echo "error.. please install ${dep} to use this script" ; exit 111
-  fi
+	hash ${dep} 2>/dev/null
+	if [ $? -gt 0 ]; then
+		echo "error.. please install ${dep} to use this script"
+		exit 111
+	fi
 done
 
 args="--height=20% --no-sort --tac"
@@ -37,7 +38,8 @@ cat <<EOF
 ###############################################
 EOF
 
-pick=$(cat <<EOF | fzf ${args}
+pick=$(
+	cat <<EOF | fzf ${args}
 account
 account-and-project
 account-project-and-cluster
@@ -47,62 +49,58 @@ project-and-cluster
 EOF
 )
 
-set_account(){
-  local SELECTED_ACCOUNT="$(gcloud auth list --format="value(account)" | fzf ${args})"
-  echo "[] exec: gcloud config set account ${SELECTED_ACCOUNT}"
-  gcloud config set account ${SELECTED_ACCOUNT}
+set_account() {
+	local SELECTED_ACCOUNT="$(gcloud auth list --format="value(account)" | fzf ${args})"
+	echo "[] exec: gcloud config set account ${SELECTED_ACCOUNT}"
+	gcloud config set account ${SELECTED_ACCOUNT}
 }
 
-
-set_project(){
-  local RAW="$(gcloud alpha projects list | fzf ${args})"
-  local RAW_PROJECT="$(echo ${RAW} | awk '{print $1}')"
-  if [ ! "X${PROJECT_CURRENT}" == "X${RAW_PROJECT}" ]; then
-    echo "[] exec: gcloud config set project ${RAW_PROJECT}"
-    gcloud config set project ${RAW_PROJECT}
-  fi
+set_project() {
+	local RAW="$(gcloud alpha projects list | fzf ${args})"
+	local RAW_PROJECT="$(echo ${RAW} | awk '{print $1}')"
+	if [ ! "X${PROJECT_CURRENT}" == "X${RAW_PROJECT}" ]; then
+		echo "[] exec: gcloud config set project ${RAW_PROJECT}"
+		gcloud config set project ${RAW_PROJECT}
+	fi
 }
 
-set_cluster(){
-  PROJECT_CURRENT="$(gcloud config get-value project)"
-  local RAW="$(gcloud container clusters list 2>/dev/null | egrep "RUNNING|STATUS" | fzf ${args})"
-  local RAW_NAME="$(echo ${RAW} | awk '{print $1}')"
-  # local RAW_LOCATION="$(echo ${RAW} | awk '{print $2}' | cut -d "-" -f 1-2)"
-  local RAW_LOCATION="$(echo ${RAW} | awk '{print $2}' )"
-  echo "[] exec: gcloud beta container clusters get-credentials ${RAW_NAME} --region ${RAW_LOCATION} --project ${PROJECT_CURRENT}"
-  gcloud beta container clusters get-credentials ${RAW_NAME} --region ${RAW_LOCATION} --project ${PROJECT_CURRENT}
+set_cluster() {
+	PROJECT_CURRENT="$(gcloud config get-value project)"
+	local RAW="$(gcloud container clusters list 2>/dev/null | egrep "RUNNING|STATUS" | fzf ${args})"
+	local RAW_NAME="$(echo ${RAW} | awk '{print $1}')"
+	# local RAW_LOCATION="$(echo ${RAW} | awk '{print $2}' | cut -d "-" -f 1-2)"
+	local RAW_LOCATION="$(echo ${RAW} | awk '{print $2}')"
+	echo "[] exec: gcloud beta container clusters get-credentials ${RAW_NAME} --region ${RAW_LOCATION} --project ${PROJECT_CURRENT}"
+	gcloud beta container clusters get-credentials ${RAW_NAME} --region ${RAW_LOCATION} --project ${PROJECT_CURRENT}
 }
-
-
 
 case $pick in
-  account)
-    echo "picked account"
-    set_account
-    ;;
-  account-and-project)
-    echo "picked account"
-    set_account
-    set_project
-    ;;
-  account-project-and-cluster)
-    echo "picked account"
-    set_account
-    set_project
-    set_cluster
-    ;;
-  project)
-    echo "picked project"
-    set_project
-    ;;
-  cluster)
-    echo "picked cluster"
-    set_cluster
-    ;;
-  project-and-cluster)
-    echo "picked project + cluster"
-    set_project
-    set_cluster
-    ;;
+account)
+	echo "picked account"
+	set_account
+	;;
+account-and-project)
+	echo "picked account"
+	set_account
+	set_project
+	;;
+account-project-and-cluster)
+	echo "picked account"
+	set_account
+	set_project
+	set_cluster
+	;;
+project)
+	echo "picked project"
+	set_project
+	;;
+cluster)
+	echo "picked cluster"
+	set_cluster
+	;;
+project-and-cluster)
+	echo "picked project + cluster"
+	set_project
+	set_cluster
+	;;
 esac
-
diff --git a/bin/kcns b/bin/kcns
--- a/bin/kcns
+++ b/bin/kcns
@@ -17,7 +17,6 @@
 #
 #   0. You just DO WHAT THE FUCK YOU WANT TO.
 
-
 ######## OK legal over..
 #
 # Q: What does this do?
@@ -48,97 +47,89 @@
 #
 # kcns
 
-
 set -e
 
+function usage() {
+	fname="$(sed "s+.*\/++" <<<$0)"
+	cat <<-EOF
+		Hello and welcome to the official
 
-function usage(){
-  fname="$(sed "s+.*\/++" <<<$0)"
-cat <<-EOF
-Hello and welcome to the official
+		 "Kube Change NS" docs:
 
- "Kube Change NS" docs:
+		---
+		Usage:
+		$ $fname <namespace-you-want>
+		---
 
----
-Usage:
-$ $fname <namespace-you-want>
----
+		🙃 <-- obligitory emoji.. now this project is cool
 
-🙃 <-- obligitory emoji.. now this project is cool
+		Have a nice day
+	EOF
 
-Have a nice day
-EOF
-
-exit 0
+	exit 0
 }
 
-function pick_namespace(){
-  DATA="$(kubectl get namespace -o=custom-columns=NAME:.metadata.name 2>/dev/null| grep -v ^NAME | fzf)"
-  RC=$?
-  if [ $RC -gt 0 ] ; then
-    echo "Error running 'kubectl get namespace'"
-    exit $RC
-  fi
-  echo ${DATA}
+function pick_namespace() {
+	DATA="$(kubectl get namespace -o=custom-columns=NAME:.metadata.name 2>/dev/null | grep -v ^NAME | fzf)"
+	RC=$?
+	if [ $RC -gt 0 ]; then
+		echo "Error running 'kubectl get namespace'"
+		exit $RC
+	fi
+	echo ${DATA}
 }
 
-function get_current_user(){
-  local NAME="$(kubectl config view -o jsonpath='{.users[0].name}' 2>/dev/null)"
-  if [ $? -gt 0 ]; then
-    echo nil
-  else
-    echo ${NAME}
-  fi
+function get_current_user() {
+	local NAME="$(kubectl config view -o jsonpath='{.users[0].name}' 2>/dev/null)"
+	if [ $? -gt 0 ]; then
+		echo nil
+	else
+		echo ${NAME}
+	fi
 }
 
-function get_current_cluster(){
-  local STRING="$(kubectl config current-context)"
+function get_current_cluster() {
+	local STRING="$(kubectl config current-context)"
 
-  if grep -q "/" <<<${STRING} ; then
-    # "/" chars detected, lets assume the cluster/root context is the LEFT
-    local CLUSTER="$(cut -d "/" -f 1 <<<${STRING})"
-  else
-    local CLUSTER=$STRING
-  fi
-  echo $CLUSTER
+	if grep -q "/" <<<${STRING}; then
+		# "/" chars detected, lets assume the cluster/root context is the LEFT
+		local CLUSTER="$(cut -d "/" -f 1 <<<${STRING})"
+	else
+		local CLUSTER=$STRING
+	fi
+	echo $CLUSTER
 }
 
-
-
-function config_set_context(){
-  kubectl \
-    config set-context \
-    "${3}" \
-    --cluster=${1} \
-    --namespace=${2}
+function config_set_context() {
+	kubectl \
+		config set-context \
+		"${3}" \
+		--cluster=${1} \
+		--namespace=${2}
 }
 
-
-function config_set_context_with_user(){
-  kubectl \
-    config set-context \
-    "${3}" \
-    --cluster=${1} \
-    --namespace=${2} \
-    --user=${4}
+function config_set_context_with_user() {
+	kubectl \
+		config set-context \
+		"${3}" \
+		--cluster=${1} \
+		--namespace=${2} \
+		--user=${4}
 }
 
-
-function config_use_context(){
-  kubectl config use-context "${1}"
+function config_use_context() {
+	kubectl config use-context "${1}"
 }
 
 ###################
-if [ X$1 == "X-h" ]     ;then  usage ; fi
-if [ X$1 == "X--help" ] ;then  usage ; fi
-
+if [ X$1 == "X-h" ]; then usage; fi
+if [ X$1 == "X--help" ]; then usage; fi
 
 if [ ! X$1 == X ]; then
-  NAMESPACE="${1}"
+	NAMESPACE="${1}"
 else
-  NAMESPACE=$(pick_namespace)
+	NAMESPACE=$(pick_namespace)
 fi
-
 
 CLUSTER=$(get_current_cluster)
 USERNAME="$(get_current_user)"
@@ -146,13 +137,13 @@ USERNAME="$(get_current_user)"
 echo c=${CLUSTER},u=${USERNAME}
 
 if [ X${USERNAME} == Xnil ]; then
-  # no username.. ok lets roll without it.. (tsk tsk)
-  NEW_CONTEXT="${CLUSTER}/${NAMESPACE}"
-  config_set_context "${CLUSTER}" "${NAMESPACE}" "${NEW_CONTEXT}"
+	# no username.. ok lets roll without it.. (tsk tsk)
+	NEW_CONTEXT="${CLUSTER}/${NAMESPACE}"
+	config_set_context "${CLUSTER}" "${NAMESPACE}" "${NEW_CONTEXT}"
 else
-  # you are a good person with a username
-  NEW_CONTEXT="${CLUSTER}/${NAMESPACE}"
-  config_set_context_with_user "${CLUSTER}" "${NAMESPACE}" "${NEW_CONTEXT}" "${USERNAME}"
+	# you are a good person with a username
+	NEW_CONTEXT="${CLUSTER}/${NAMESPACE}"
+	config_set_context_with_user "${CLUSTER}" "${NAMESPACE}" "${NEW_CONTEXT}" "${USERNAME}"
 fi
 
 # use it
diff --git a/bin/kx b/bin/kx
--- a/bin/kx
+++ b/bin/kx
@@ -27,7 +27,7 @@ IFS=$'\n\t'
 KUBECTX="${HOME}/.kube/kubectx"
 
 usage() {
-  cat <<"EOF"
+	cat <<"EOF"
 USAGE:
   kubectx                       : list the contexts
   kubectx <NAME>                : switch to context <NAME>
@@ -40,180 +40,179 @@ USAGE:
 
   kubectx -h,--help         : show this message
 EOF
-  exit 1
+	exit 1
 }
 
 current_context() {
-  kubectl config view -o=jsonpath='{.current-context}'
+	kubectl config view -o=jsonpath='{.current-context}'
 }
 
 get_contexts() {
-  kubectl config get-contexts -o=name | sort -n
+	kubectl config get-contexts -o=name | sort -n
 }
 
 list_contexts() {
-  set -u pipefail
-  local cur
-  cur="$(current_context)"
+	set -u pipefail
+	local cur
+	cur="$(current_context)"
 
-  local yellow darkbg normal
-  yellow=$(tput setaf 3)
-  darkbg=$(tput setab 0)
-  normal=$(tput sgr0)
+	local yellow darkbg normal
+	yellow=$(tput setaf 3)
+	darkbg=$(tput setab 0)
+	normal=$(tput sgr0)
 
-  local cur_ctx_fg cur_ctx_bg
-  cur_ctx_fg=${KUBECTX_CURRENT_FGCOLOR:-$yellow}
-  cur_ctx_bg=${KUBECTX_CURRENT_BGCOLOR:-$darkbg}
+	local cur_ctx_fg cur_ctx_bg
+	cur_ctx_fg=${KUBECTX_CURRENT_FGCOLOR:-$yellow}
+	cur_ctx_bg=${KUBECTX_CURRENT_BGCOLOR:-$darkbg}
 
+	local selected=$(get_contexts | grep -v "\/" | sort | fzf)
+	if [ ! X${selected} == X ]; then
+		set_context ${selected}
+	fi
 
-  local selected=$(get_contexts | grep -v "\/" | sort | fzf)
-  if [ ! X${selected} == X ]; then
-    set_context ${selected}
-  fi
-
-  # # more than one IP found, let the human pick
-  # # sorry about the crazy shell stuff....
-  # select cluster in $list "quit"; do
-  # case $cluster in
-  #   "quit")
-  #     break
-  #   ;;
-  #   *)
-  #     # echo set "${cluster}"
-  #     set_context "${cluster}"
-  #     exit $?
-  #   ;;
-  # esac
-  # done
+	# # more than one IP found, let the human pick
+	# # sorry about the crazy shell stuff....
+	# select cluster in $list "quit"; do
+	# case $cluster in
+	#   "quit")
+	#     break
+	#   ;;
+	#   *)
+	#     # echo set "${cluster}"
+	#     set_context "${cluster}"
+	#     exit $?
+	#   ;;
+	# esac
+	# done
 
 }
 
 read_context() {
-  if [[ -f "${KUBECTX}" ]]; then
-    cat "${KUBECTX}"
-  fi
+	if [[ -f "${KUBECTX}" ]]; then
+		cat "${KUBECTX}"
+	fi
 }
 
 save_context() {
-  local saved
-  saved="$(read_context)"
+	local saved
+	saved="$(read_context)"
 
-  if [[ "${saved}" != "${1}" ]]; then
-    printf %s "${1}" > "${KUBECTX}"
-  fi
+	if [[ "${saved}" != "${1}" ]]; then
+		printf %s "${1}" >"${KUBECTX}"
+	fi
 }
 
 switch_context() {
-  kubectl config use-context "${1}"
+	kubectl config use-context "${1}"
 }
 
 set_context() {
-  local prev
-  prev="$(current_context)"
+	local prev
+	prev="$(current_context)"
 
-  switch_context "${1}"
+	switch_context "${1}"
 
-  if [[ "${prev}" != "${1}" ]]; then
-    save_context "${prev}"
-  fi
+	if [[ "${prev}" != "${1}" ]]; then
+		save_context "${prev}"
+	fi
 }
 
 swap_context() {
-  local ctx
-  ctx="$(read_context)"
-  if [[ -z "${ctx}" ]]; then
-    echo "error: No previous context found." >&2
-    exit 1
-  fi
-  set_context "${ctx}"
+	local ctx
+	ctx="$(read_context)"
+	if [[ -z "${ctx}" ]]; then
+		echo "error: No previous context found." >&2
+		exit 1
+	fi
+	set_context "${ctx}"
 }
 
 user_of_context() {
-  # TODO(ahmetb) no longer used, consider deleting
-  kubectl config view \
-    -o=jsonpath="{.contexts[?(@.name==\"${1}\")].context.user}"
+	# TODO(ahmetb) no longer used, consider deleting
+	kubectl config view \
+		-o=jsonpath="{.contexts[?(@.name==\"${1}\")].context.user}"
 }
 
 cluster_of_context() {
-  # TODO(ahmetb) no longer used, consider deleting
-  kubectl config view \
-    -o=jsonpath="{.contexts[?(@.name==\"${1}\")].context.cluster}"
+	# TODO(ahmetb) no longer used, consider deleting
+	kubectl config view \
+		-o=jsonpath="{.contexts[?(@.name==\"${1}\")].context.cluster}"
 }
 
 context_exists() {
-  grep -q ^"${1}"\$ <(kubectl config get-contexts -o=name)
+	grep -q ^"${1}"\$ <(kubectl config get-contexts -o=name)
 }
 
 rename_context() {
-  local old_name="${1}"
-  local new_name="${2}"
+	local old_name="${1}"
+	local new_name="${2}"
 
-  if [[ "${old_name}" == "." ]]; then
-    old_name="$(current_context)"
-  fi
+	if [[ "${old_name}" == "." ]]; then
+		old_name="$(current_context)"
+	fi
 
-  # TODO(ahmetb) old_user and old_cluster are no longer used, clean up
-  local old_user old_cluster
-  old_user="$(user_of_context "${old_name}")"
-  old_cluster="$(cluster_of_context "${old_name}")"
-  if [[ -z "$old_user" || -z "$old_cluster" ]]; then
-    echo "error: Cannot retrieve context ${old_name}."  >&2
-    exit 1
-  fi
+	# TODO(ahmetb) old_user and old_cluster are no longer used, clean up
+	local old_user old_cluster
+	old_user="$(user_of_context "${old_name}")"
+	old_cluster="$(cluster_of_context "${old_name}")"
+	if [[ -z "$old_user" || -z "$old_cluster" ]]; then
+		echo "error: Cannot retrieve context ${old_name}." >&2
+		exit 1
+	fi
 
-  if context_exists "${new_name}"; then
-    echo "Context \"${new_name}\" exists, deleting..." >&2
-    kubectl config delete-context "${new_name}" 1>/dev/null 2>&1
-  fi
+	if context_exists "${new_name}"; then
+		echo "Context \"${new_name}\" exists, deleting..." >&2
+		kubectl config delete-context "${new_name}" 1>/dev/null 2>&1
+	fi
 
-  kubectl config rename-context "${old_name}" "${new_name}"
+	kubectl config rename-context "${old_name}" "${new_name}"
 }
 
 delete_contexts() {
-  IFS=' ' read -ra CTXS <<< "${1}"
-  for i in "${CTXS[@]}"; do
-    delete_context "${i}"
-  done
+	IFS=' ' read -ra CTXS <<<"${1}"
+	for i in "${CTXS[@]}"; do
+		delete_context "${i}"
+	done
 }
 
 delete_context() {
-  local ctx
-  ctx="${1}"
-  if [[ "${ctx}" == "." ]]; then
-    ctx="$(current_context)"
-  fi
-  echo "Deleting context \"${ctx}\"..." >&2
-  kubectl config delete-context "${ctx}"
+	local ctx
+	ctx="${1}"
+	if [[ "${ctx}" == "." ]]; then
+		ctx="$(current_context)"
+	fi
+	echo "Deleting context \"${ctx}\"..." >&2
+	kubectl config delete-context "${ctx}"
 }
 
 main() {
-  if [[ "$#" -eq 0 ]]; then
-    list_contexts
-  elif [[ "${1}" == "-d" ]]; then
-    if [[ "$#" -lt 2 ]]; then
-      echo "error: missing context NAME" >&2
-      usage
-    fi
-    delete_contexts "${@:2}"
-  elif [[ "$#" -gt 1 ]]; then
-    echo "error: too many arguments" >&2
-    usage
-  elif [[ "$#" -eq 1 ]]; then
-    if [[ "${1}" == "-" ]]; then
-      swap_context
-    elif [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
-      usage
-    elif [[ "${1}" =~ ^-(.*) ]]; then
-      echo "error: unrecognized flag \"${1}\"" >&2
-      usage
-    elif [[ "${1}" =~ (.+)=(.+) ]]; then
-      rename_context "${BASH_REMATCH[2]}" "${BASH_REMATCH[1]}"
-    else
-      set_context "${1}"
-    fi
-  else
-    usage
-  fi
+	if [[ "$#" -eq 0 ]]; then
+		list_contexts
+	elif [[ "${1}" == "-d" ]]; then
+		if [[ "$#" -lt 2 ]]; then
+			echo "error: missing context NAME" >&2
+			usage
+		fi
+		delete_contexts "${@:2}"
+	elif [[ "$#" -gt 1 ]]; then
+		echo "error: too many arguments" >&2
+		usage
+	elif [[ "$#" -eq 1 ]]; then
+		if [[ "${1}" == "-" ]]; then
+			swap_context
+		elif [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
+			usage
+		elif [[ "${1}" =~ ^-(.*) ]]; then
+			echo "error: unrecognized flag \"${1}\"" >&2
+			usage
+		elif [[ "${1}" =~ (.+)=(.+) ]]; then
+			rename_context "${BASH_REMATCH[2]}" "${BASH_REMATCH[1]}"
+		else
+			set_context "${1}"
+		fi
+	else
+		usage
+	fi
 }
 
 main "$@"
